{% macro test_macros() %}
  {% do test_connection_id_validation() %}
  {% do test_provider_descriptors() %}
  {% do test_alloydb_connection_resolution() %}
  {% do test_spanner_metadata_connection_resolution() %}
  {% do test_connection_rejects_defaults_block() %}
  {% do test_schema_is_required_when_omitted() %}
  {% do test_quote_safe_and_mixed_case_identifiers() %}
  {% do test_quote_literal_doubles_single_quotes() %}
  {% do test_spanner_quote_literal_uses_googlesql_escapes() %}
  {% do test_external_query_renders_without_planning() %}
  {% do test_postgres_metadata_remote_sql() %}
  {% do test_alloydb_metadata_uses_postgres_profile() %}
  {% do test_metadata_external_query_wrapper() %}
  {% do test_spanner_metadata_uses_dedicated_connection() %}
  {% do test_federated_relation_pin_path_is_stable() %}
  {% do test_schema_diff_detects_add_remove_change() %}
  {% do test_schema_diff_no_changes() %}
  {% do test_schema_diff_user_defined_udt_matches_pin_type() %}
  {% do test_schema_diff_report_includes_precision_scale() %}
  {% do test_schema_diff_ignores_integer_information_schema_precision() %}
  {% do test_schema_diff_ignores_float_information_schema_precision() %}
  {% do test_schema_diff_normalizes_timestamp_aliases() %}
  {% do test_schema_diff_normalizes_varchar_aliases() %}
  {% do test_schema_diff_detects_character_maximum_length_change() %}
  {% do test_schema_diff_report_omits_integer_precision() %}
  {% do test_yaml_double_quoted_escapes_special_characters() %}
  {% do test_plan_all_native_passthrough() %}
  {% do test_plan_uuid_jsonb_safe_projection() %}
  {% do test_plan_uuid_strict_errors() %}
  {% do test_plan_unknown_type_errors() %}
  {% do test_plan_bounded_numeric_passthrough() %}
  {% do test_plan_mixed_decimals_safe_projects_offender() %}
  {% do test_plan_mixed_decimals_strict_errors() %}
  {% do test_plan_mixed_bignumeric_and_unbounded_keeps_option() %}
  {% do test_plan_all_bignumeric_passthrough() %}
  {% do test_plan_mixed_remaining_decimals_safe_keeps_option() %}
  {% do test_plan_uuid_override_remote_cast() %}
  {% do test_plan_missing_pin_errors() %}
  {% do test_plan_type_overrides_money_under_strict() %}
  {% do test_plan_empty_and_duplicate_pins_error() %}
  {% do test_plan_bit_native_passthrough() %}
  {% do test_plan_pg_lsn_safe_remote_cast() %}
  {% do test_plan_search_types_safe_remote_cast() %}
  {% do test_plan_integer_array_unknown_errors() %}
  {% do test_plan_json_native_passthrough() %}
  {% do test_plan_type_overrides_uuid_uppercase_under_strict() %}
  {% do test_plan_numeric_typmod_errors_with_precision_scale_hint() %}
  {% do test_plan_unsafe_remote_type_errors() %}
  {% do test_plan_user_defined_udt_name_classifies_uuid() %}
  {% do test_plan_array_udt_name_does_not_replace_data_type() %}
  {% do test_plan_from_ir_postgres_type_matrix() %}
  {% do test_plan_from_ir_alloydb_type_matrix_matches_postgres() %}
  {% do test_plan_from_ir_alloydb_orders() %}
  {% do test_plan_from_ir_spanner_type_matrix() %}
  {% do test_plan_from_ir_spanner_orders_native() %}
  {% do test_plan_from_ir_spanner_struct_still_fails() %}
  {% do test_plan_from_ir_postgres_udt_uuid() %}
  {% do test_alloydb_postgres_plan_uses_shared_profile() %}
  {% do test_alloydb_postgres_router_matches_postgres_dialect() %}
  {% do test_alloydb_postgres_live_plan_conformance() %}
  {% do test_postgres_type_map_keys_match_expected_matrix() %}
  {% do test_postgres_type_entry_matrix() %}
  {% do test_postgres_alias_to_bigquery_target_matrix() %}
  {% do test_postgres_post_cast_to_bigquery_target_matrix() %}
  {% do test_postgres_numeric_typmod_preserved() %}
  {% do test_postgres_unknown_type_entry() %}
  {% do test_postgres_render_remote_cast_smoke() %}
  {% do test_spanner_google_provider_descriptor() %}
  {% do test_spanner_google_metadata_query() %}
  {% do test_spanner_google_type_mapping() %}
  {% do test_spanner_google_type_length_modifiers_to_bigquery_target() %}
  {% do test_spanner_google_render_remote_cast_smoke() %}
  {% do test_spanner_google_sql_rendering() %}
  {% do test_spanner_google_live_plan_native_types() %}
  {% do test_spanner_google_struct_cannot_federate() %}
  {% do test_spanner_pinned_federated_relation_renders_priority() %}
  {% do test_federated_relation_renders_passthrough() %}
  {% do test_federation_inspect_reports_pushdown() %}
  {% do test_federation_inspect_strict_requires_overrides() %}
  {% do test_federation_inspect_forwards_plan_errors() %}
{% endmacro %}
